name = "Perso"
description = "Mon propre theme et basta"
license = "MIT"
homepage = ""
min_version = "0.12.0"
demo = ""

[extra]

[author]
name = "Quentin Amirault"
homepage = "https://amrltqt.github.io"
